"""Pure renderers over the command table (docs/design/command-table.md): the
plugin's slash-command pages and the README's command reference. Plain data
in, plain data out; `cli._dev_commands` is the edge that reads and writes files.
"""

from __future__ import annotations

import argparse
import json
from collections.abc import Sequence
from typing import NamedTuple

from agent_tools.commands import Arg, Command, Group

Table = Sequence[tuple[Group, Sequence[Command]]]

BEGIN = "<!-- commands:begin (generated by `cox dev commands render`; do not edit) -->"
END = "<!-- commands:end -->"

_NO_VALUE = frozenset({"store_true", "store_false", "count"})


class Entry(NamedTuple):
    """One invocable command: a row, or a group with no rows (a leaf)."""

    command: str
    args: tuple[Arg, ...]
    summary: str
    examples: tuple[str, ...]


def arg_usage(arg: Arg) -> str | None:
    """`arg` as a usage line writes it; None for a suppressed argument."""
    kw = arg.kwargs
    flag = arg.flags[0]
    choices = kw.get("choices")
    token = kw.get("metavar") or ("|".join(map(str, choices)) if choices else flag.lstrip("-").replace("-", "_").upper())
    nargs = kw.get("nargs")
    positional = {"?": f"[{token}]", "*": f"[{token}...]", "+": f"{token}..."}.get(nargs, token)
    bare = flag if kw.get("action") in _NO_VALUE else f"{flag} {token}"
    optional = bare if kw.get("required") else f"[{bare}]"
    shown = positional if not flag.startswith("-") else optional
    return None if kw.get("help") == argparse.SUPPRESS else shown


def usage(command: str, args: Sequence[Arg]) -> str:
    return " ".join([command, *filter(None, map(arg_usage, args))])


def _entries(group: Group, rows: Sequence[Command]) -> list[Entry]:
    return (
        [Entry(f"cox {group.name} {r.name}", r.args, r.summary, r.examples) for r in rows]
        if rows
        else [Entry(f"cox {group.name}", group.args, group.help, ())]
    )


def readme_line(entry: Entry) -> str:
    """The first example when the row has one, else the usage derived from its args."""
    shown = entry.examples[0] if entry.examples else usage(entry.command, entry.args)
    return f"{shown}   {entry.summary}"


def render_readme_block(table: Table) -> str:
    """One line per command in table order, in a fenced block."""
    lines = [readme_line(e) for group, rows in table for e in _entries(group, rows)]
    return "```\n" + "\n".join(lines) + "\n```\n"


def splice(text: str, block: str) -> str | None:
    """`text` with the span between the two marker comments replaced by
    `block`; None when either marker is missing or they are out of order."""
    start, end = text.find(BEGIN), text.find(END)
    return None if start < 0 or end < start else text[: start + len(BEGIN)] + "\n" + block + text[end:]


def render_page(row: Command) -> str:
    """The plugin slash-command page for one `slash=True` row."""
    hint = " ".join(filter(None, map(arg_usage, row.args)))
    examples = ["", "Examples:", "", "```", *row.examples, "```"] if row.examples else []
    return "\n".join([
        "---",
        f"description: {json.dumps(row.summary)}",
        f"argument-hint: {json.dumps(hint)}",
        "---",
        "",
        f"Run `cox {row.group} {row.name} $ARGUMENTS` and report what it prints.",
        "",
        row.summary,
        *examples,
    ]) + "\n"


def render_pages(table: Table) -> dict[str, str]:
    """file name -> page, for every `slash=True` row."""
    return {f"{r.name}.md": render_page(r) for _, rows in table for r in rows if r.slash}
